[features]
seeds = false
[programs.localnet]
art_sol = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/sumit/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
